# simple exception;
try:
  print(x)
except:
  print("An exception occurred")